version: 2.1
jobs:

  test:
    docker:
      - image: cimg/node:20.10.0

    steps:
      - checkout
      - run: npm install npm@10.2.5
      - run: npm ci
      - run: CI=true npm run test

workflows:
  version: 2
  test:
    jobs:
      - test:
          filters:
            branches:
              only:
                - master
                - develop
